services:
  app:
    container_name: marvin-whatsapp-bot
    build:
      context: .
      dockerfile: Dockerfile
    image: marvin-whats-bot:latest
    volumes:
      - app_data:/app  
      - yarn_cache:/root/.cache/yarn  
    environment:
      NODE_ENV: "production"
    command: ["node","."]
    
volumes:
  app_data: 
  yarn_cache: 
