version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - yarn_cache:/root/.cache/yarn
    environment:
      NODE_ENV: "production"
    command: ["node", "--env-file=.env", "."]
    
volumes:
  yarn_cache:  
